### ISSUE TITLE
Update for the instructions to boot Xinu?

### ISSUE THREAD

**Issue by Kikou1998** [jarrocha/XinuBBB#3]
The entire guide could be followed and produce a working Xinu on BBB except for the `uEnv.txt` file:
`bootfile=xinu.boot `
`boot_mmc=fatload mmc 0 0x81000000 ${bootfile}; bootm 0x81000000`
`uenvcmd=run boot_mmc
`
The second address 0x81000000 is missing from the `uEnv.txt` original guide, which should be added if you are using the latest version of uboot. 
(Maybe uboot has updated some of its semantics as of June 2021? If my assumption is wrong please point it out)

How to find the address: 
After `make` in Xinu compile folder, the address will be printed as shown below:
<img width="607" alt="Screen Shot 2021-06-12 at 12 58 19 AM" src="https://user-images.githubusercontent.com/40484986/121723740-7a375680-cb19-11eb-9b23-6a5011a0bbf7.png">

For network boot, it seems that 

ipaddr=10.10.10.10
serverip=10.10.10.1
netmask=255.255.255.0
bootfile=xinu.boot
boot_mmc=tftp ${bootfile}; bootm 0x82000000
uenvcmd=run boot_mmc

the bootm should be followed by an address specifying the memory location.

**Comment by jarrocha** [comment]
Hello @Kikou1998, sorry for the delayed reply. I was taking a long vacation. Thank you for the feedback. I'll add this to the main instructions. I have seen cases where the initial memory address is different. That's why I recommend using the first step because depending on the version of u-boot or its configuration, the initial address may be different for some people. When I was first doing this, I encountered this situation too. I'll add this to the guide. Thanks again.

**Comment by jarrocha** [comment]
Sorry it took this long. I tested your results and added them to the README. Thanks again.
